<?php

$plugin = array(
  'title' => t('960/16 6-10'),
  'category' => t('960gs: 16'),
  'icon' => 'icon.png',
  'css' => '../../../../lib/grid.css',
  'theme' => '960_16_610',
  'regions' => array(
    'top' => t('Top'),
	  'aboveLeft' => t('Above Left'),
    'aboveRight' => t('Above Right'),
	  'middle' => t('Middle'),
	  'belowLeft' => t('Below Left'),
	  'belowRight' => t('Below Right'),
	  'bottom' => t('Bottom')
  ),
);
