<?php

$plugin = array(
  'title' => t('960/24 7-10-7'),
  'category' => t('960gs: 24'),
  'icon' => 'icon.png',
  'css' => '../../../../lib/grid.css',
  'theme' => '960_24_7107',
  'regions' => array(
    'top' => t('Top'),
    'aboveLeft' => t('Above Left'),
    'aboveCenter' => t('Above Center'),
    'aboveRight' => t('Above Right'),
    'middle' => t('Middle'),
    'belowLeft' => t('Below Left'),
    'belowCenter' => t('Below Center'),
    'belowRight' => t('Below Right'),
    'bottom' => t('Bottom')
  ),
);