<?php

$plugin = array(
  'title' => t('960/16 4-4-4-4'),
  'category' => t('960gs: 16'),
  'icon' => 'icon.png',
  'css' => '../../../../lib/grid.css',
  'theme' => '960_16_4444',
  'regions' => array(
    'top' => t('Top'),
    'aboveLeft' => t('Above Left'),
    'aboveLeftCenter' => t('Above Left Center'),
    'aboveRightCenter' => t('Above Right Center'),
    'aboveRight' => t('Above Right'),
    'middle' => t('Middle'),
    'belowLeft' => t('Below Left'),
    'belowLeftCenter' => t('Below Left Center'),
    'belowRightCenter' => t('Below Right Center'),
    'belowRight' => t('Below Right'),
    'bottom' => t('Bottom')
  ),
);