<?php

$plugin = array(
  'title' => t('960/16 5-6-7-6 5-6-13 Left Sidebar'),
  'category' => t('960gs: 24'),
  'icon' => 'icon.png',
  'css' => '../../../../lib/grid.css',
  'theme' => '960_24_5676_5613_leftSb',
  'regions' => array(
    'alpha' => t('Alpha'),
    'leftSb' => t('Left Sidebar'),
    'top' => t('Top'),
    'topLeft' => t('Top Left'),
    'topCenter' => t('Top Center'),
    'topRight' => t('Top Right'),
    'aboveLeft' => t('Above Left'),
    'aboveRight' => t('Above Right'),
    'middle' => t('Middle'),
    'belowLeft' => t('Below Left'),
    'belowRight' => t('Below Right'),
    'bottomLeft' => t('Bottom Left'),
    'bottomCenter' => t('Bottom Center'),
    'bottomRight' => t('Bottom Right'),
    'bottom' => t('Bottom'),
    'omega' => t('Omega'),
  ),
);
